#!/usr/bin/env node
/**
 * Test suite for gstin-core.js — run with:  node --test tests/
 *
 * Every GSTIN literal used here was generated by gstin-core.js itself and then
 * independently confirmed against python-stdnum's Luhn mod 36 (see
 * tools/crosscheck.mjs + tools/verify_gstin.py).
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const C = require('../gstin-core.js');

// state 27 | state 29 | state 07 | state 24 | state 36 | state 28 (retired) | state 38
const VALID = ['27AAPFU0939F1ZV', '29AAICP2912R1ZR', '07AAACR5055K1Z9',
  '24AAACT2727Q1Z2', '36AABCT1332L1ZF', '28AAPFU0939F1ZT', '38AAACL1234B1Z4'];

// --- check digit -----------------------------------------------------------

test('checkDigit reproduces the check digit of known-valid GSTINs', () => {
  for (const g of VALID) {
    assert.equal(C.checkDigit(g.slice(0, 14)), g[14], `${g} check digit`);
    assert.ok(C.checksumOk(g), `${g} checksum`);
  }
});

test('checkDigit rejects malformed input instead of returning junk', () => {
  assert.equal(C.checkDigit('27AAPFU0939F1'), null);      // too short
  assert.equal(C.checkDigit('!!!!!'), null);              // not in the charset
  assert.equal(C.checkDigit('27AAPFU0939F1!'), null);     // one illegal character
  assert.equal(C.checkDigit('27aapfu0939f1z'), 'V');      // lowercase is normalised, not rejected
});

test('checksumOk catches a wrong final character', () => {
  assert.ok(!C.checksumOk('27AAPFU0939F1ZO'));
  assert.ok(!C.checksumOk('27AAPFU0939F1ZA'));
  assert.ok(!C.checksumOk('27AAPFU0939F1Z'));
  assert.ok(!C.checksumOk('27AAPFU0939F1ZVX'));
});

test('parity trap: the check digit is computed over head + "0"', () => {
  // Guarding the bug that this file originally had: folding over the head alone
  // gives a plausible but wrong digit. '27AAPFU0939F1Z' must yield 'V', not 'T'.
  assert.equal(C.checkDigit('27AAPFU0939F1Z'), 'V');
  assert.notEqual(C.checkDigit('27AAPFU0939F1Z'), 'T');
});

test('luhnMod36 over a complete valid number is zero', () => {
  for (const g of VALID) assert.equal(C.luhnMod36(g), 0, g);
});

// --- decode ----------------------------------------------------------------

test('decode returns state, PAN, entity type and name initial', () => {
  const d = C.decode('27AAPFU0939F1ZV');
  assert.equal(d.valid, true);
  assert.equal(d.stateCode, '27');
  assert.equal(d.stateName, 'Maharashtra');
  assert.equal(d.pan, 'AAPFU0939F');
  assert.equal(d.panEntityCode, 'F');
  assert.equal(d.panEntity, 'Firm / LLP');
  assert.equal(d.nameInitial, 'U');
  assert.equal(d.entityNumber, '1');
  assert.equal(d.formatted, '27 AAPFU 0939 F 1 Z V');
  assert.deepEqual(d.issues, []);
});

test('decode reads the newest state codes', () => {
  assert.equal(C.decode('38AAACL1234B1Z4').stateName, 'Ladakh');
  assert.equal(C.decode('36AABCT1332L1ZF').stateName, 'Telangana');
  assert.equal(C.decode('37AAACL1234B1Z6').stateName, 'Andhra Pradesh');
});

test('decode explains each failure instead of just saying invalid', () => {
  const short = C.decode('27AAPFU0939F1Z');
  assert.equal(short.valid, false);
  assert.ok(short.issues.some((i) => i.code === 'length'));

  const badState = C.decode('99AAPFU0939F1ZV');
  assert.ok(badState.issues.some((i) => i.code === 'state'));

  const badSum = C.decode('27AAPFU0939F1ZO');
  assert.ok(badSum.issues.some((i) => i.code === 'checksum'));
  assert.match(badSum.issues.find((i) => i.code === 'checksum').message, /Expected "V"/);
});

test('a non-Z 14th character is a warning, not a rejection', () => {
  const d = C.decode('27AAPFU0939F1AV');
  assert.ok(d.issues.some((i) => i.code === 'z' && i.level === 'warn'));
});

test('retired state codes warn and name their successor', () => {
  const d = C.decode('28AAPFU0939F1ZT');
  const w = d.issues.find((i) => i.code === 'state-retired');
  assert.ok(w);
  assert.match(w.message, /37/);
  assert.equal(d.valid, true);   // still a real GSTIN, just an old state code
});

test('normalize tolerates spaces, dashes and unicode dashes', () => {
  assert.equal(C.normalize('27-AAPFU-0939F-1ZV'), '27AAPFU0939F1ZV');
  assert.equal(C.normalize('27 AAPFU 0939F 1ZV'), '27AAPFU0939F1ZV');
  assert.equal(C.normalize('27\u2013AAPFU\u20130939F\u20131ZV'), '27AAPFU0939F1ZV');
});

// --- OCR extraction --------------------------------------------------------

test('extract finds a cleanly printed GSTIN and flags label proximity', () => {
  const got = C.extract('HIGHWAY DHABA\nGSTIN : 27AAPFU0939F1ZV\nGST 5%');
  assert.ok(got.length >= 1);
  assert.equal(got[0].gstin, '27AAPFU0939F1ZV');
  assert.equal(got[0].exact, true);
  assert.equal(got[0].labelProximity, true);
});

test('extract repairs classic Tesseract confusions', () => {
  assert.ok(C.extract('GSTIN : 27AAPFU O939 F1ZV').some((c) => c.gstin === '27AAPFU0939F1ZV'));
  assert.ok(C.extract('GSTIN : 27AAPFU0939FI ZV').some((c) => c.gstin === '27AAPFU0939F1ZV'));
  assert.ok(C.extract('GST No. 29AAICPZ912R1ZR').some((c) => c.gstin === '29AAICP2912R1ZR'));
});

test('extract survives separators and stray punctuation', () => {
  assert.ok(C.extract('GSTIN 27-AAPFU-0939F-1ZV please').some((c) => c.gstin === '27AAPFU0939F1ZV'));
  assert.ok(C.extract('GSTIN/UIN: 36.AABCT.1332L.1ZF').some((c) => c.gstin === '36AABCT1332L1ZF'));
});

test('extract ranks a labelled candidate above an unlabelled one', () => {
  const got = C.extract('random run 27AAPFU0939F1ZV ... GSTIN : 36AABCT1332L1ZF');
  assert.equal(got[0].gstin, '36AABCT1332L1ZF');
  assert.equal(got[0].labelProximity, true);
});

test('extract returns nothing for a bill with no GSTIN on it', () => {
  assert.equal(C.extract('TOTAL 674.00\nCASH\nTHANK YOU VISIT AGAIN\nTIN 123456').length, 0);
});

test('extract never invents a number out of unrelated digits', () => {
  for (const junk of ['123456789012345', '999999999999999', '000000000000000']) {
    assert.equal(C.extract(junk).length, 0, junk);
  }
});

test('extract de-duplicates the same GSTIN seen twice', () => {
  const got = C.extract('GSTIN : 27AAPFU0939F1ZV  |  GSTIN : 27AAPFU0939F1ZV');
  assert.equal(got.filter((c) => c.gstin === '27AAPFU0939F1ZV').length, 1);
});

// --- checksum repair -------------------------------------------------------

test('repairChecksum recovers a single-character OCR slip decisively', () => {
  const cases = [
    ['27AAPFUO939F1ZV', '27AAPFU0939F1ZV'],
    ['Z7AAPFU0939F1ZV', '27AAPFU0939F1ZV'],
    ['07AAACRS055K1Z9', '07AAACR5055K1Z9'],
    ['29AAICP29I2R1ZR', '29AAICP2912R1ZR']
  ];
  for (const [input, want] of cases) {
    const r = C.repairChecksum(input);
    assert.equal(r.best, want, input);
    assert.equal(r.bestDistance, 1, input);
    assert.equal(r.ambiguous, false, input);
  }
});

test('repairChecksum refuses to guess when nothing fits', () => {
  const r = C.repairChecksum('27AAPFU0939F1ZQ');   // 'Q' can never be the check digit here
  assert.equal(r.best, null);
  assert.equal(r.solutions.length, 0);
});

test('repairChecksum skips an input that already passes', () => {
  const r = C.repairChecksum('27AAPFU0939F1ZV');
  assert.equal(r.best, '27AAPFU0939F1ZV');
  assert.equal(r.ambiguous, false);
});

test('repairChecksum bails out instead of exploding on a huge search space', () => {
  const r = C.repairChecksum('2ZAA8CTI332L1ZF', 4);   // tiny budget
  assert.equal(r.skipped, true);
  assert.equal(r.best, null);
});

// --- verdict ---------------------------------------------------------------

test('composition dealer charging GST is illegal, with a refund figure', () => {
  const v = C.verdict({ status: C.STATUS.COMPOSITION, verified: true, taxCharged: true, taxableValue: 641.9, taxAmount: 32.1 });
  assert.equal(v.level, 'illegal');
  assert.equal(v.cannotCollect, true);
  assert.equal(v.refundable, 32.1);
  assert.match(v.headline, /not collectible/i);
  assert.ok(v.legal.length >= 2);
  assert.ok(v.legal.some((l) => /Section 10\(4\)/.test(l)));
});

test('composition service provider under 10(2A) is equally barred', () => {
  const v = C.verdict({ status: C.STATUS.COMPOSITION_SERVICES, verified: true, taxCharged: true, taxAmount: 150 });
  assert.equal(v.level, 'illegal');
  assert.equal(v.refundable, 150);
});

test('composition dealer not charging GST is exactly right', () => {
  const v = C.verdict({ status: C.STATUS.COMPOSITION, verified: true, taxCharged: false, invoiceKind: 'bill-of-supply' });
  assert.equal(v.level, 'ok');
  assert.match(v.headline, /Correctly billed/i);
});

test('composition dealer issuing a tax invoice is a warning', () => {
  const v = C.verdict({ status: C.STATUS.COMPOSITION, verified: true, taxCharged: false, invoiceKind: 'tax-invoice' });
  assert.equal(v.level, 'warn');
  assert.ok(v.lines.some((l) => /Rule 5/.test(l)));
});

test('regular taxpayer charging 5% restaurant GST checks out end to end', () => {
  const v = C.verdict({ status: C.STATUS.REGULAR, verified: true, taxCharged: true, taxableValue: 641.9, taxAmount: 32.1 });
  assert.equal(v.level, 'ok');
  assert.equal(v.cannotCollect, false);
  assert.equal(v.refundable, 0);
  assert.deepEqual(v.rate, { rate: 5, plausible: true });
});

test('an implausible implied rate is surfaced on the bill', () => {
  const v = C.verdict({ status: C.STATUS.REGULAR, verified: true, taxCharged: true, taxableValue: 1000, taxAmount: 95 });
  assert.equal(v.rate.plausible, false);
  assert.ok(v.lines.some((l) => /9\.5%/.test(l)));
});

test('suspended, cancelled and not-found suppliers cannot collect', () => {
  for (const s of [C.STATUS.SUSPENDED, C.STATUS.CANCELLED, C.STATUS.INVALID]) {
    const v = C.verdict({ status: s, verified: true, taxCharged: true, taxAmount: 100 });
    assert.equal(v.level, 'illegal', s);
  }
});

test('unverified status never claims a legal conclusion', () => {
  const v = C.verdict({ taxCharged: true, taxAmount: 32.1 });
  assert.equal(v.level, 'unknown');
  assert.equal(v.verified, false);
  assert.equal(v.cannotCollect, false);
});

test('a no-tax bill from a regular supplier is fine', () => {
  const v = C.verdict({ status: C.STATUS.REGULAR, verified: true, taxCharged: false });
  assert.equal(v.level, 'ok');
  assert.match(v.headline, /No GST on this bill/i);
});

test('money formats in the Indian grouping style', () => {
  assert.equal(C.money(1234567.5), '12,34,567.50');
  assert.equal(C.money(null), '0');
});
